name: api_request_manager
description: "A package made as a helper for http package. Uses requests timeout, returns maps with request results and logs requests results if requested."
version: 0.0.1

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0